### ISSUE TITLE
Whatsapp button with wrong data-title

### ISSUE THREAD

**Issue by marcosegato** [ayozehd/sharer#3]
Hello,

Whatsapp button has incoherent "data-title" value always set as "1", while all the other buttons have the blog title post.
This is what happens when sharing ("1" in the text box and "${1}" in the link preview):
![immagine](https://user-images.githubusercontent.com/6240628/67125009-2b2a0880-f1f4-11e9-9b19-aa1960981377.png)

Thanks, Marco

**Comment by ayozehd** [comment]
Thanks for report it Marco. There's a new release [1.2.1](https://github.com/ayozehd/grav-plugin-sharer/releases/tag/1.2.1) which solves that and other minor issues too. Try to upgrade and check how is your plugin configuration. In the yaml array `buttons` remove `whatsapp.title: true` if exists. Let me know if you need some help to find it.

**Comment by marcosegato** [comment]
Hello Ayoze, I tried the new version and also removed the line you said. Unfortunately I had a big regression, none of the buttons now is sharing anything: I always get empty title and empty data content.
Tried to clean Grav's cache and reinstall the plugin but nothing has changed.
Let me know if you need any other information.

**Comment by ayozehd** [comment]
There was a template collision on `template/macros/macros.html.twig` in some themes. Update to [1.2.2](github.com/ayozehd/grav-plugin-sharer/releases/tag/1.2.2)

**Comment by marcosegato** [comment]
I confirm the issue is solved, thank you very much for you work!
