### ISSUE TITLE
How-To Add hero image?

### ISSUE THREAD

**Issue by jason-unleashed** [ayozehd/sharer#7]
Beautiful plugin, but I'm having an issue with the images.  Currently, I'm using a quark-blog theme and the images for each blog are a background image.  These aren't getting passed to the social sites.  

Is there a way to add the background/hero image to this plugin?  Something like {{ page.media.images|first }}?

https://www.testing.unleashedfinancial.com/articles/the-national-housing-market

Thanks,
J

**Comment by ayozehd** [comment]
Unfortunately, there's no any option to include a background image from settings. But you can customize the CSS of your site adding a custom property to `.sharer-buttons-toolbar` class. 
Look at screenshot how I did:
![image](https://user-images.githubusercontent.com/37075876/82540255-a830ae00-9b46-11ea-9ecc-00fdfe43d381.png)

**Comment by jason-unleashed** [comment]
Thanks for the quick reply.  I didn't ask the right question.  It's not the background image I want to add to the sharer toolbar, it's including the background image when sharing to Facebook, twitter, and Linkedin.  

Here is the result when I share an article on Facebook.
<img alt="current result" src="https://user-images.githubusercontent.com/21330145/82569334-f3da5c00-9b34-11ea-8462-47a0e0e6979d.png" width="200"/>

But this is the desired result:
<img alt="desired result" src="https://user-images.githubusercontent.com/21330145/82569468-24ba9100-9b35-11ea-897f-5de389e942cd.png" width="200"/>

Most of my articles don't have images in the body, only the hero/background image.  In the few that do have images in the body, when I share the initial screen looks like it includes the first image in the body but when it arrives at Facebook there is no image.  

Share:
<img alt="pre-share with a body image" src="https://user-images.githubusercontent.com/21330145/82570553-9a732c80-9b36-11ea-985b-3173b057aaf2.png" width="200"/>

Result:
<img alt="actual share" src="https://user-images.githubusercontent.com/21330145/82570645-b971be80-9b36-11ea-9343-7a6f3890d0a6.png" width="200"/>

Thanks,
J

**Comment by jason-unleashed** [comment]
Nevermind.  I found my problem.  Helps to have the og: metatags setup.
